### ISSUE TITLE
上传商品出现问题

### ISSUE THREAD

**Issue by bianxiangg** [Anduin2017/TravelIC#1]
数据库：localDB
操作系统：win 7 sp1
过程：按照ReadMe搭建好后，访问产品上传页面，http://localhost:5000/Products/Create，出现错误

> An unhandled exception occurred while processing the request.
NullReferenceException: Object reference not set to an instance of an object.
TravelInCloud.Controllers.ProductsController+<Create>d__9.MoveNext()，

在VS2017中调试后，认为是在下步中出问题

```
public async Task<IActionResult> Create([Bind("ProductId,ProductDetails,ProductInfo,ProductName,ProductWarnning")] Product product)
        {
            var _user = await GetCurrentUserAsync() as Store;
            if (ModelState.IsValid)
            {
                product.OwnerId = _user.Id;
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(CreateImage), new { id = product.ProductId });
            }
            return View(product);
        }
```
GetCurrentUserAsync()方法返回的类型是ApplicationUser，Store是其子类，转换失败，_user=null，所以product.OwnerID = _user.Id，取不到值，报错。

改为
```
public async Task<IActionResult> Create([Bind("ProductId,ProductDetails,ProductInfo,ProductName,ProductWarnning")] Product product)
        {
            var tempUser = await GetCurrentUserAsync();
            var _user = new Store(tempUser);
            if (ModelState.IsValid)
            {
                product.OwnerId = _user.Id;
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(CreateImage), new { id = product.ProductId });
            }
            return View(product);
        }
```
之后，上述错误消失，出现如下错误

> An unhandled exception occurred while processing the request.

InvalidCastException: Unable to cast object of type 'TravelInCloud.Models.ApplicationUser' to type 'TravelInCloud.Models.Store'.
Microsoft.EntityFrameworkCore.Metadata.Internal.ClrPropertySetter.SetClrValue(object instance, object value)

经调试，错误卡在这一句 _context.Add(product)，感觉可能跟模型的外键有关系，现无法解决

**Comment by Anduin2017** [comment]
You shouldn't change the code. Your should revert your changes. Your code may cause come unacceptable errors.

Your problem is how to upload a product. When you are about to create a product, please make sure current user is a store user not a typical user. Please check if current user is a store user. If not, please apply a store user.

**Comment by bianxiangg** [comment]
哪个页面可以注册商户账户？http://localhost:5000/Account/register 是不注册的都是普通用户

**Comment by bianxiangg** [comment]
已经找到在个人中心->账户设置->商店设置->申请开店
